### ISSUE TITLE
Asked to overwrite an unused filename [BUG].

### ISSUE THREAD

**Issue by awmc000** [proh14/ptext#20]
**Describe the bug**
The program says that a filename already exists and asks the user if they want to overwrite it when in fact the filename does not already exist.

**To Reproduce**
1. Clone
2. Make
3. Run the executable without any arguments, like `./ptext`
4. Save to a filename that is not used, like "hello-world" or anything not in the directory

**Expected behavior**

**Screenshots**

![image](https://github.com/proh14/ptext/assets/98981929/c88c4aec-9f00-4d8c-b6c1-59f2c9ef651e)
![image](https://github.com/proh14/ptext/assets/98981929/fec3a6d2-a866-43c9-be90-564663ada2f5)

**Desktop**
 - OS Distro: Ubuntu
 - Version 22.04.3 LTS
 - Shell: zsh 5.8.1
 - Terminal: Tilix
 - DE: GNOME 42.9

**Comment by proh14** [comment]
Thanks for letting me know, fixed in f841ea8906eec007fd5d5724829767fe2e2d26f1
