### ISSUE TITLE
Segmentation fault when trying to create new file [BUG]

### ISSUE THREAD

**Issue by FliegendeWurst** [proh14/ptext#22]
**Describe the bug**
When trying to create a new file, ptext crashes with a segfault.

**To Reproduce**
1. Clone, build with default options
2. Run `ptext /tmp/some-new-file.txt`

**Expected behavior**
Should not crash, instead create the file when saving.

**Desktop**
 - OS Distro: NixOS 24.05

**Comment by proh14** [comment]
Hello :) Thank you for reporting. 

I fixed it in a481bfcc325370c665b9a535f3a5ff4083b42dc7

**Comment by proh14** [comment]
Also I am really sorry for this childish problem, I don't really have time for ptext nowadays :)
