### ISSUE TITLE
Add a keybind to delete a whole line[FEATURE].

### ISSUE THREAD

**Issue by proh14** [proh14/ptext#4]
**Is your feature request related to a problem? Please describe.**
I want the editor to delete a whole line when someone presses CTRL + x

**Describe the solution you'd like**
The key can be added to src/input.c in the procKey function. And the line can be deleted with the delRow function.

**Comment by Jetas18** [comment]
can you assign the issue to me?

**Comment by proh14** [comment]
sure

**Comment by Jetas18** [comment]
which file has the shortcut to exit and save the file? I will add the shortcut there

**Comment by proh14** [comment]
for now in input.c in prockey function

**Comment by BenHerbst** [comment]
I need this too

**Comment by Jetas18** [comment]
@proh14 sorry I wont be able to do it, I have recently gotten busy with something else :(( Really sorry

**Comment by proh14** [comment]
Added in 87f9561b300a971bc7697631a872fcd14f4d2147
