### ISSUE TITLE
could you add nano keybindings?

### ISSUE THREAD

**Issue by osevan** [proh14/ptext#5]
Can you add nano keybindings or config file where we can change everything self before configure and make? 

Thanks and

Best  regards

**Comment by proh14** [comment]
Hello @osevan. my goal for a plugin's system is to load so(DLLs) at the startup but if you want nano keybindings i can surely add them!

**Comment by proh14** [comment]
@osevan take a look at #6

**Comment by osevan** [comment]
I want every shortcut keys from nano editor.

**Comment by proh14** [comment]
@osevan did you check #6?

**Comment by proh14** [comment]
any was fixed in #6 now you can add your keybinds easily.

**Comment by osevan** [comment]
> any was fixed in #6 now you can add your keybinds easily.

Big thx.
But could you show us Example how to do this?

**Comment by proh14** [comment]
> > any was fixed in #6 now you can add your keybinds easily.
> 
> Big thx. But could you show us Example how to do this?

I will add comments

**Comment by proh14** [comment]
> > any was fixed in #6 now you can add your keybinds easily.
> 
> Big thx. But could you show us Example how to do this?

Comments added in the latest config.c
